spring.application.name=spring-ai-intro

#Pass API key as environment variable, e.g. -DGROQ_API_KEY=your-api-key
#spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.api-key="not-needed"

# default (not needed if using OpenAi server https://api.openai.com))
# spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.base-url=${LOCAL_BASE_URL}
spring.ai.openai.chat.options.model=${LOCAL_DEFAULT_MODEL}
